### ISSUE TITLE
L'encodage du RSS GeoRezo est incorrect

### ISSUE THREAD

**Issue by Guts** [Guts/elgeopaso#11]
Après #13, le flux semble bien reparti mais tout ne fonctionne pas correctement (en indiquant une longueur https://georezo.net/extern.php?fid=10&show=50) :

![image](https://user-images.githubusercontent.com/1596222/76201463-943a0900-61f3-11ea-9fc6-8adad1331098.png)

Cela ressemble fortement à un problème d'encodage des caractères :

![image](https://user-images.githubusercontent.com/1596222/76201889-47a2fd80-61f4-11ea-8cfa-b6924d1a12aa.png)

Côté serveur, voici ce que j'ai dans les logs :

```log
RSS feed is badly formed. Parser error: document declared as utf8, but parsed as iso-8859-2.
```

A noter que c'est bien encodé sur le forum. @yjacolin vous ne faites plus d'UTF 8 dans les flux ?

----

_Originally posted by @Guts in https://github.com/Guts/elpaso/issues/33#issuecomment-596432270_

**Comment by biratchet** [comment]
Dans un premier temps, on peut essayer de corriger les offres avec les caractères de remplacement. S'il y en a trop, on pourra changer notre fusil d'épaule dans un deuxième temps.
A voir avec Marco et l'équipe qui modère, sachant que les corrections pourraient être faite par d'autres membres de l'asso.
