### ISSUE TITLE
Le flux RSS de GeoRezo est corrompu par une offre de décembre

### ISSUE THREAD

**Issue by Guts** [Guts/elgeopaso#129]
# Constat

Un utilisateur m'a indiqué que le site n'affichait plus les offres parues après le 22 décembre :

![image](https://user-images.githubusercontent.com/1596222/103583767-a1da2100-4ee0-11eb-9741-0cc51a7046f3.png)

Le problème vient du flux : https://georezo.net/extern.php?fid=10&show=100

# Traces

Dans Firefox :

![image](https://user-images.githubusercontent.com/1596222/103583849-c3d3a380-4ee0-11eb-8ed5-c52c6392c13b.png)

Erreur relevée dans les journaux d'El Geo Paso :

```log
WARNING || 20268 139683167467328 || georezo_rss_parser - 263 || parse_new_offers || Parser raised a non blocking error. Investigating...
ERROR || 20268 139683167467328 || georezo_rss_parser - 291 || parse_new_offers || Feed error is not recognized: <unknown>:203:1713: not well-formed (invalid token). Aborting parsing of 'https://georezo.net/extern.php?fid=10&show=100'
```

Le validateur du W3C indique un certain nombre d'erreurs : https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgeorezo.net%2Fextern.php%3Ffid%3D10%26show%3D100. En descendant à la ligne indiquée (203), on voit bien où est le souci :

```
This feed does not validate.

    line 203, column 1713: XML parsing error: <unknown>:203:1713: not well-formed (invalid token) [help]

        ... ier les missions suivantes :&lt;br /&gt;- D&amp;amp;eacute;ploiement et ...
                                                     ^
```

# Diagnostic

C'est cette offre qui corrompt le flux : https://georezo.net/forum/viewtopic.php?pid=338439#p338439

@marcisenmann peux-tu regarder pour nettoyer les probables balises Word ou autre de cette annonce stp, en particulier là o c'est indiqué dans l'erreur juste au-dessus ?

**Comment by biratchet** [comment]
Salut les amis,
Je viens de dégager la balise pourrie d'ESRI.
Pas vu d'autres, @Guts dis-nous si OK de ton coté, car je ne connais pas la fréquence du moissonnage.
A+

**Comment by Guts** [comment]
> Je viens de dégager la balise pourrie d'ESRI.
> Pas vu d'autres, @Guts dis-nous si OK de ton coté, car je ne connais pas la fréquence du moissonnage.

Merci @biratchet :+1: 

Par contre, ça ne suffit toujours pas... Tu peux vérifier en rafraichissant le validateur https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgeorezo.net%2Fextern.php%3Ffid%3D10%26show%3D100

**Comment by Guts** [comment]
> Pas vu d'autres, @Guts dis-nous si OK de ton coté, car je ne connais pas la fréquence du moissonnage.

Toutes les heures.

**Comment by yjacolin** [comment]
corrigé ce qui posait encore problème mais il faut attendre la fin du cache de notre coté.

**Comment by Guts** [comment]
> corrigé ce qui posait encore problème mais il faut attendre la fin du cache de notre coté.

Super, merci !

C'était quoi le souci ?

**Comment by Guts** [comment]
Tout est rentré dans l'ordre : 

![image](https://user-images.githubusercontent.com/1596222/103623347-4c316300-4f38-11eb-9267-eced9990c606.png)

**Comment by yjacolin** [comment]
Un apostrophe dans le titre d'une autre offre !

**Comment by Guts** [comment]
Ok, merci !

**Comment by biratchet** [comment]
Merci @yjacolin je ne l'avais pas vu!
