### ISSUE TITLE
Contenu des offres en archive

### ISSUE THREAD

**Issue by marcisenmann** [Guts/elgeopaso#132]
Salut les amis,
Il me semblait que c'était le cas mais je me trompe peut-être. Il serait bien de pouvoir consulter le contenu complet des offres qui sont archivées ici :
https://elgeopaso.georezo.net/jobs/search/
En effet, nous recevons de plus en plus de tickets d'utilisateurs qui souhaiteraient revoir le contenus d'une ou plusieurs offres d'emploi. Avec les possibilités de recherches multi-critères dans Archives, ce serait très utile de consulter en plus les contenus.
Merci Julien pour ton avis expert !

Marco

**Comment by marcisenmann** [comment]
Oups, j'ai oublié mon propre ticket antérieur sur cette question :
https://github.com/Guts/elgeopaso/issues/81
Désolé Julien

**Comment by Guts** [comment]
Pas de souci, un rappel à l'ordre c'est pas mal et ça prouve que le besoin est toujours vivace.
Je t'avoue par contre que j'aimerais déjà que les problèmes d'encodage soient réglés du côté de GeoRezo parce-que le contenu est clairement pas beau à voir!

Duplicate of #81

**Comment by marcisenmann** [comment]
ok ! Concernant le soucis d'encodage (notre "bête noire"), j'ai espoir qu'Yves trouve une solution pour le corriger.

Marc
