### ISSUE TITLE
Flux RSS corrompu

### ISSUE THREAD

**Issue by Guts** [Guts/elgeopaso#176]
Hello @yjacolin @biratchet @marcisenmann 

Le flux est toujours planté : https://georezo.net/extern.php?fid=10&show=100

**Comment by yjacolin** [comment]
boom.

Y.

**Comment by biratchet** [comment]
Désolé, je n'étais pas dispo hier.

**Comment by Guts** [comment]
> Désolé, je n'étais pas dispo hier.

Pas de souci, Yves a géré et c'est désormais revenu à la "normale" (moyennant les caractères spéciaux tjs). The show can go on!
