### ISSUE TITLE
Offres Esri France toujours mal formatées

### ISSUE THREAD

**Issue by Guts** [Guts/elgeopaso#179]
Le flux RSS est encore planté à cause des offres Esri France du 19 juillet.

ping @yjacolin @biratchet @marcisenmann 

https://georezo.net/extern.php?fid=10&show=100

**Comment by yjacolin** [comment]
Annonce fixée, reste à supprimer le cache. Tu serais dispo en août pour tester le nouveau flux qui, je l'espère, pourrait corriger ce genre de problème ?
Y.

**Comment by Guts** [comment]
> Annonce fixée, reste à supprimer le cache. 

Merci, c'est bien passé dans le tuyau.

> Tu serais dispo en août pour tester le nouveau flux qui, je l'espère, pourrait corriger ce genre de problème ?

On en parle en privé plutôt ? Pas trop envie d'exposer ma vie aoûtienne en public ;)
