### ISSUE TITLE
elgeopaso.georezo.net injoignable

### ISSUE THREAD

**Issue by pierreloicq** [Guts/elgeopaso#237]
c'est triste

**Comment by Guts** [comment]
Bonsoir,

En effet, le site est down depuis mi-novembre. Nous essayons de trouver le temps de le remettre d'aplomb mais ça demande des ressources de temps bénévole que je n'ai pas ou plus...

Voyons les choses positivement : ça permet de se rendre compte que des gens l'utilisaient ! :wink:

**Comment by biratchet** [comment]
Je partage votre tristesse.
Les limites du bénévolat, malheureusement peu valorisé dans le monde pro. Dans le monde, il doit exister des entreprises (publiques ou privés) qui valident qu'un salarié prend 2 ou 3h/semaine pour travailler sur "ses projets". Je dois rêver debout.

**Comment by pierreloicq** [comment]
Du coup c'est une extinction volontaire ? 
Si non, qu'est ce qui empêche l'appli de vivre sa vie sur heroku (sur un compte gratuit d'après la doc ?) ?
merci

**Comment by biratchet** [comment]
Pour ma part, je préfèrerai t'envoyer une belle boite de chocolats, @Guts, si cela te motive pour trouver les quelques heures qu'il faut pour relancer cette très précieuse ressource ;)

**Comment by Guts** [comment]
Près d'un an plus tard, l'application est de nouveau joignable (merci @yjacolin), même s'il manque certains morceaux fonctionnels. 

Une certaine dynamique semble naître pour pérenniser le projet.

Espérons que cela lui permette de retrouver des couleurs (et je ne parle pas que de la carte #98 :wink: ).

**Comment by pierreloicq** [comment]
Congrats !

**Comment by biratchet** [comment]
Yes, Yves a fait un super boulot, il doit rester 10% du boulot pour retrouver 100% des fonctionnalités.
Et Julien a donné les éléments à l'AFIGéO pour estimer le coût des différentes maintenances qui permettraient à cette ressource d'être pérennisée.
