### ISSUE TITLE
Archives : ordre d'affichage

### ISSUE THREAD

**Issue by marcisenmann** [Guts/elgeopaso#31]
Ce serait bien que l'affichage des archives des offres (ici https://elgeopaso.georezo.net/jobs/search/) se fassent plutôt des plus récentes aux plus anciennes. 
Avec si possible un tri via le titre des champs (Titre ; date de publications, type de contrat ; lieu...).

Merci !

Marco

**Comment by biratchet** [comment]
Salut Marco,
Monsieur devient exigeant ;)
Pense à attribuer le ticket, sinon...

**Comment by marcisenmann** [comment]
C'est que que l'on attribue ?

**Comment by Guts** [comment]
Bonne idée, je vais appliquer le tri par défaut.

Mais activer le tri sur les colonnes demande un peu trop de temps pour que je puisse m'en occuper rapidement.

**Comment by marcisenmann** [comment]
Pas de problème Julien. Ca attendra...
As-tu pris connaissance du petite communiqué d'info ? Il ne reste plus que ton retour pour publier.
merci,
Marco

**Comment by Guts** [comment]
C'est en préprod : https://el-geo-paso-search-sort-zehmv8.herokuapp.com/jobs/search/

ça te va @marcisenmann ?

**Comment by Guts** [comment]
Allez hop, je prends ce silence pour un oui !

**Comment by marcisenmann** [comment]
Oui, c'est impeccable. 
Marco
