### ISSUE TITLE
Flux RSS en panne

### ISSUE THREAD

**Issue by Guts** [Guts/elgeopaso#33]
Hola,

Jour d'annonce, jour de bug !

Le RSS https://georezo.net/extern.php?fid=10&show=10 ne renvoie rien :

Chromium : 

![image](https://user-images.githubusercontent.com/1596222/80382865-1f09bc80-88a3-11ea-88b0-f45dade054f1.png)

Firefox :

![image](https://user-images.githubusercontent.com/1596222/80382967-43659900-88a3-11ea-9155-85d8effc6ddc.png)

Message d'erreur :

```
Erreur d’analyse XML : données incompréhensibles après l’élément de document
Emplacement : https://georezo.net/extern.php?fid=10&show=10
Numéro de ligne 2, Colonne 1 :
<b>Warning</b>:  include(/var/www/html//web/blog/config_geoblogrss.php): failed to open stream: No such file or directory in <b>/var/www/html/web/extern.php</b> on line <b>359</b><br />
^
```

**Comment by biratchet** [comment]
Je confirme, mais seul Yves peut trouver la solution.
C'est également KO sur DécryptaGéo

**Comment by Guts** [comment]
Ça finira bien par revenir. Et puis ça prouve au moins que mes améliorations de mars ont rendu El Géo Paso plus robuste et indépendant du RSS :)

**Comment by yjacolin** [comment]
corrigé, mais il y a toujours les problèmes d'encodage qui ne sont pas liés au flux RSS, on les retrouve dans le message initial.

**Comment by yjacolin** [comment]
et le bug était là depuis lontemps :)

**Comment by Guts** [comment]
L'erreur semble en fait bcp plus sérieuse. Certes le site ne plante pas, mais le flux semble vide :

```xml
<?xml version="1.0" encoding="UTF8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<title>GeoRezo.net</title>
		<link>https://georezo.net/</link>
		<description><![CDATA[GeoRezo.net, le Portail de la Géomatique et des SIG (Systèmes d'Information Géographique)]]></description>
		<atom:link href="http://georezo.net/extern.php?fid=10&amp;show=50" rel="self" type="application/rss+xml"/>
		<language>fr</language>
		<image>
			<url>https://georezo.net/img/logo/logo_small_georezo.gif</url>
			<title>GeoRezo.net</title>
			<link>https://georezo.net/</link>
			<width>120</width>
			<height>30</height>
			<description><![CDATA[GeoRezo.net, le Portail de la Géomatique et des SIG (Systèmes d'Information Géographique)]]></description>
		</image>
		<lastBuildDate>Thu, 01 Jan 1970 01:00:00 +0100</lastBuildDate>
		<generator>GeoRezo</generator>
		<ttl>60</ttl>
	</channel>
</rss>
 ```

**Comment by biratchet** [comment]
Je confirme: le flux est toujours KO sur https://decryptageo.fr (bandeau gauche)

**Comment by yjacolin** [comment]
C'est une régression dû à la panne d'hier. L'image docker n'était pas à jour. J'ai remodifié dans le container et récupère la nouvelle image.

**Comment by yjacolin** [comment]
j'ai réussi à corriger pas mal de problème :) Tu peux relancer un import ?
