### ISSUE TITLE
Offre en doublon

### ISSUE THREAD

**Issue by Guts** [Guts/elgeopaso#55]
Dites-moi ces 2 offres ne sont-elles pas strictement identiques ?

- https://georezo.net/forum/viewtopic.php?id=120013
- https://georezo.net/forum/viewtopic.php?id=120014

En parlant du 13 @marcisenmann , tu t'es grillé !

**Comment by marcisenmann** [comment]
Oui vu ce matin mais pas corrigée. On a parfois un bug dans le module de moderation : l'offre peut être publiée et rester sur la console et être à nouveau publiée. Je vais supprimer une des deux. Merci
